# Config file for lsf cluster

# Configuration file version (do not change)
config_version: 7

# Source files
# Path to an ENSEMBL FASTA reference genome file/URL to be used for read mapping (local, FTP or HTTP)
genome:
# Path to an ENSEMBL GFF3 annotation file/URL containing transcript annotations (local, FTP or HTTP)
annotation:
# Path to an ENSEMBL cDNA FASTA reference transcriptome file/URL to be used for read counting (local, FTP or HTTP)
transcriptome:
# Path to a tabulated sample sheet
sample_sheet:

# cluster command for lsf
cluster_cores: 10000
cluster_nodes: 500
cluster_cmd: "bsub -q {cluster.queue} -n {cluster.threads} -M {cluster.mem} -J {cluster.name} -oo {cluster.output} -eo {cluster.error}"

# DEFAULT CLUSTER OPTIONS
__default__:
    threads: 2
    mem: 5000
    queue: "research-rh74"

# INPUT FILES RULES
get_genome:
    opt: ""
    threads: 2
    mem: 5000
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

get_transcriptome:
    opt: ""
    threads: 2
    mem: 5000
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

get_annotation:
    opt: ""
    threads: 2
    mem: 5000
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

fastp:
    opt: ""
    threads: 16
    mem: 10000
    name : "nanosnake_RNA_illumina.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

# GENOME ALIGNMENT RULES
star_index:
    opt: ""
    threads: 20
    mem: 50000
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

star_align:
    opt: "--outFilterType BySJout  --outFilterMultimapNmax 20 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000"
    threads: 20
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

pbt_alignment_filter:
    opt: "--min_align_len 50 --min_freq_identity 0.7 --skip_unmapped --skip_secondary --skip_supplementary"
    threads: 2
    mem: 5000
    name : "nanosnake_RNA_illumina.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"


star_count_merge:
    opt: ""
    threads: 2
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

# OPTIONAL RULES (comment to be skiped)
# cufflinks:
#     opt: "--library-type fr-firststrand --upper-quartile-norm"
#     threads: 20
#     mem: 20000

# cufflinks_fpkm_merge:
#     opt: ""
#     mem: 20000
#     name : "nanosnake_RNA_illumina.{rule}"
#     output : "logs/{rule}/bsub_stdout.log"
#     error : "logs/{rule}/bsub_stderr.log"

subread_featurecounts:
    opt: "-p"
    threads: 20
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

subread_featurecounts_merge:
    opt: ""
    threads: 2
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

samtools_qc:
    opt: ""
    threads: 2
    mem: 10000
    name : "nanosnake_RNA_illumina.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

bedtools_genomecov:
    opt: "-bg"
    threads: 2
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

igvtools_count:
    opt: "-w 10"
    threads: 2
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

# TRANSCRIPTOME PSEUDO-ALIGNMENT RULES
salmon_index:
    opt: ""
    threads: 20
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"

salmon_quant:
    opt: "--libType A --validateMappings"
    threads: 20
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}.{wildcards.sample}"
    output : "logs/{rule}/{wildcards.sample}_bsub_stdout.log"
    error : "logs/{rule}/{wildcards.sample}_bsub_stderr.log"

salmon_count_merge:
    opt: ""
    threads: 2
    mem: 20000
    name : "nanosnake_RNA_illumina.{rule}"
    output : "logs/{rule}/bsub_stdout.log"
    error : "logs/{rule}/bsub_stderr.log"
